inst_classes = [
    '__background__', 'person', 'bicycle', 'car', 'motorcycle', 'airplane', 'bus',
    'train', 'truck', 'boat', 'traffic light', 'fire hydrant', 'N/A', 'stop sign',
    'parking meter', 'bench', 'bird', 'cat', 'dog', 'horse', 'sheep', 'cow',
    'elephant', 'bear', 'zebra', 'giraffe', 'N/A', 'backpack', 'umbrella', 'N/A', 'N/A',
    'handbag', 'tie', 'suitcase', 'frisbee', 'skis', 'snowboard', 'sports ball',
    'kite', 'baseball bat', 'baseball glove', 'skateboard', 'surfboard', 'tennis racket',
    'bottle', 'N/A', 'wine glass', 'cup', 'fork', 'knife', 'spoon', 'bowl',
    'banana', 'apple', 'sandwich', 'orange', 'broccoli', 'carrot', 'hot dog', 'pizza',
    'donut', 'cake', 'chair', 'couch', 'potted plant', 'bed', 'N/A', 'dining table',
    'N/A', 'N/A', 'toilet', 'N/A', 'tv', 'laptop', 'mouse', 'remote', 'keyboard', 'cell phone',
    'microwave', 'oven', 'toaster', 'sink', 'refrigerator', 'N/A', 'book',
    'clock', 'vase', 'scissors', 'teddy bear', 'hair drier', 'toothbrush'
]


indices_animal_detection = [
    inst_classes.index("bird"),
    inst_classes.index("cat"),
    inst_classes.index("dog"),
    inst_classes.index("horse"),
    inst_classes.index("sheep"),
    inst_classes.index("cow"),
    inst_classes.index("elephant"),
    inst_classes.index("bear"),
    inst_classes.index("zebra"),
    inst_classes.index("giraffe"),
    inst_classes.index("bench"), # TODO
]


colors = {
    "Black": (0,0,0),
    "White": (255,255,255),
    "Yellow": (255,255,0),
    "Gray": (128,128,128),
    "Saddlebrown": (139, 69, 19),
    "Orange": (255,165,0),
    "Wheat": (245,222,179),
    "Vanilla": (243, 229, 171),
}

colors_vec = list(colors.values())
colors_names = list(colors.keys())
colors_index = {i: colors_names[i] for i in range(len(colors))}


tails_converter = {
    "Japanese_spaniel": "short",
    "Pekinese": "short",
    "Blenheim_spaniel": "short",
    "toy_terrier": "short",
    "Rhodesian_ridgeback": "long",
    "basset": "long",
    "beagle": "long",
    "bluetick": "long",
    "black-and-tan_coonhound": "long",
    "Walker_hound": "long",
    "English_foxhound": "long",
    "redbone": "long",
    "borzoi": "long",
    "Norwegian_elkhound": "short",
    "Scottish_deerhound": "long",
    "Weimaraner": "short",
    "Staffordshire_bullterrier": "short",
    "American_Staffordshire_terrier": "short",
    "Border_terrier": "short",
    "Irish_terrier": "long",
    "Norfolk_terrier": "short",
    "Norwich_terrier": "short",
    "Yorkshire_terrier": "short",
    "wire-haired_fox_terrier": "short",
    "Lakeland_terrier": "short",
    "Airedale": "short",
    "cairn": "short",
    "giant_schnauzer": "short",
    "standard_schnauzer": "short",
    "soft-coated_wheaten_terrier": "short",
    "soft-coated_wheaten_terrier": "short",
    "West_Highland_white_terrier": "short",
    "flat-coated_retriever": "long",
    "golden_retriever": "long",
    "Labrador_retriever": "long",
    "Chesapeake_Bay_retriever": "long",
    "Irish_setter": "long",
    "Gordon_setter": "long",
    "Brittany_spaniel": "short",
    "Welsh_springer_spaniel": "short",
    "cocker_spaniel": "short",
    "Sussex_spaniel": "long",
    "Irish_water_spaniel": "short",
    "briard": "long",
    "kelpie": "long",
    "Shetland_sheepdog": "short",
    "collie": "short",
    "Rottweiler": "short",
    "Doberman": "short",
    "boxer": "short",
    "Tibetan_mastiff": "long",
    "malamute": "long",
    "Siberian_husky": "long",
    "pug": "short",
    "Leonberg": "long",
    "Newfoundland": "long",
    "Great_Pyrenees": "long",
    "Samoyed": "short",
    "Pomeranian": "short",
    "chow": "short",
    "standard_poodle": "short",
    "dingo": "long",
}

breeds_converter = {
    0: 'Japanese_spaniel',
    1: 'Pekinese',
    2: 'Blenheim_spaniel',
    3: 'toy_terrier',
    4: 'Rhodesian_ridgeback',
    5: 'basset',
    6: 'beagle',
    7: 'bluetick',
    8: 'black-and-tan_coonhound',
    9: 'Walker_hound',
    10: 'redbone',
    11: 'borzoi',
    12: 'Weimaraner',
    13: 'Staffordshire_bullterrier',
    14: 'American_Staffordshire_terrier',
    15: 'Irish_terrier',
    16: 'Norfolk_terrier',
    17: 'Yorkshire_terrier',
    18: 'Lakeland_terrier',
    19: 'cairn',
    20: 'soft-coated_wheaten_terrier',
    21: 'flat-coated_retriever',
    22: 'golden_retriever',
    23: 'Labrador_retriever',
    24: 'Irish_setter',
    25: 'Brittany_spaniel',
    26: 'Welsh_springer_spaniel',
    27: 'cocker_spaniel',
    28: 'Irish_water_spaniel',
    29: 'kelpie',
    30: 'Shetland_sheepdog',
    31: 'collie',
    32: 'Rottweiler',
    33: 'Doberman',
    34: 'boxer',
    35: 'Tibetan_mastiff',
    36: 'malamute',
    37: 'Siberian_husky',
    38: 'pug',
    39: 'Newfoundland',
    40: 'Great_Pyrenees',
    41: 'Pomeranian',
    42: 'chow',
    43: 'standard_poodle',
}
