inst_classes = [
    '__background__', 'person', 'bicycle', 'car', 'motorcycle', 'airplane', 'bus',
    'train', 'truck', 'boat', 'traffic light', 'fire hydrant', 'N/A', 'stop sign',
    'parking meter', 'bench', 'bird', 'cat', 'dog', 'horse', 'sheep', 'cow',
    'elephant', 'bear', 'zebra', 'giraffe', 'N/A', 'backpack', 'umbrella', 'N/A', 'N/A',
    'handbag', 'tie', 'suitcase', 'frisbee', 'skis', 'snowboard', 'sports ball',
    'kite', 'baseball bat', 'baseball glove', 'skateboard', 'surfboard', 'tennis racket',
    'bottle', 'N/A', 'wine glass', 'cup', 'fork', 'knife', 'spoon', 'bowl',
    'banana', 'apple', 'sandwich', 'orange', 'broccoli', 'carrot', 'hot dog', 'pizza',
    'donut', 'cake', 'chair', 'couch', 'potted plant', 'bed', 'N/A', 'dining table',
    'N/A', 'N/A', 'toilet', 'N/A', 'tv', 'laptop', 'mouse', 'remote', 'keyboard', 'cell phone',
    'microwave', 'oven', 'toaster', 'sink', 'refrigerator', 'N/A', 'book',
    'clock', 'vase', 'scissors', 'teddy bear', 'hair drier', 'toothbrush'
]


indices_animal_detection = [
    inst_classes.index("bird"),
    inst_classes.index("cat"),
    inst_classes.index("dog"),
    inst_classes.index("horse"),
    inst_classes.index("sheep"),
    inst_classes.index("cow"),
    inst_classes.index("elephant"),
    inst_classes.index("bear"),
    inst_classes.index("zebra"),
    inst_classes.index("giraffe"),
    inst_classes.index("bench"), # TODO
]

colors = {
    "Black": (0,0,0),
    "White": (255,255,255),
    "Red": (255,0,0),
    "Lime": (0,255,0),
    "Blue": (0,0,255),
    "Yellow": (255,255,0),
    "Cyan/Aqua": (0,255,255),
    "Magenta/Fuchsia": (255,0,255),
    "Silver": (192,192,192),
    "Gray": (128,128,128),
    "Maroon": (128,0,0),
    "Olive": (128,128,0),
    "Green": (0,128,0),
    "Purple": (128,0,128),
    "Teal": (0,128,128),
    "Navy": (0,0,128),
    "Orange": (255,165,0),
}


colors_vec = list(colors.values())
colors_names = list(colors.keys())
colors_index = {i: colors_names[i] for i in range(len(colors))}


tails_converter = {
    "Japanese_spaniel": "short",
    "Pekinese": "short",
    "Blenheim_spaniel": "short",
    "toy_terrier": "short",
    "Rhodesian_ridgeback": "long",
    "basset": "long",
    "beagle": "long",
    "bluetick": "long",
    "black-and-tan_coonhound": "long",
    "Walker_hound": "long",
    "English_foxhound": "long",
    "redbone": "long",
    "borzoi": "long",
    "Norwegian_elkhound": "short",
    "Scottish_deerhound": "long",
    "Weimaraner": "short",
    "Staffordshire_bullterrier": "short",
    "American_Staffordshire_terrier": "short",
    "Border_terrier": "short",
    "Irish_terrier": "long",
    "Norfolk_terrier": "short",
    "Norwich_terrier": "short",
    "Yorkshire_terrier": "short",
    "wire-haired_fox_terrier": "short",
    "Lakeland_terrier": "short",
    "Airedale": "short",
    "cairn": "short",
    "giant_schnauzer": "short",
    "standard_schnauzer": "short",
    "soft-coated_wheaten_terrier": "short",
    "soft-coated_wheaten_terrier": "short",
    "West_Highland_white_terrier": "short",
    "flat-coated_retriever": "long",
    "golden_retriever": "long",
    "Labrador_retriever": "long",
    "Chesapeake_Bay_retriever": "long",
    "Irish_setter": "long",
    "Gordon_setter": "long",
    "Brittany_spaniel": "short",
    "Welsh_springer_spaniel": "short",
    "cocker_spaniel": "short",
    "Sussex_spaniel": "long",
    "Irish_water_spaniel": "short",
    "briard": "long",
    "kelpie": "long",
    "Shetland_sheepdog": "short",
    "collie": "short",
    "Rottweiler": "short",
    "Doberman": "short",
    "boxer": "short",
    "Tibetan_mastiff": "long",
    "malamute": "long",
    "Siberian_husky": "long",
    "pug": "short",
    "Leonberg": "long",
    "Newfoundland": "long",
    "Great_Pyrenees": "long",
    "Samoyed": "short",
    "Pomeranian": "short",
    "chow": "short",
    "standard_poodle": "short",
    "dingo": "long",
}

breeds_converter = {
    "0": "Japanese_spaniel",
    "1": "Pekinese",
    "2": "Blenheim_spaniel",
    "3": "toy_terrier",
    "4": "Rhodesian_ridgeback",
    "5": "basset",
    "6": "beagle",
    "7": "bluetick",
    "8": "black-and-tan_coonhound",
    "9": "Walker_hound",
    "10": "English_foxhound",
    "11": "redbone",
    "12": "borzoi",
    "13": "Norwegian_elkhound",
    "14": "Scottish_deerhound",
    "15": "Weimaraner",
    "16": "Staffordshire_bullterrier",
    "17": "American_Staffordshire_terrier",
    "18": "Border_terrier",
    "19": "Irish_terrier",
    "20": "Norfolk_terrier",
    "21": "Norwich_terrier",
    "22": "Yorkshire_terrier",
    "23": "wire-haired_fox_terrier",
    "24": "Lakeland_terrier",
    "25": "Airedale",
    "26": "cairn",
    "27": "giant_schnauzer",
    "28": "standard_schnauzer",
    "29": "soft-coated_wheaten_terrier",
    "30": "West_Highland_white_terrier",
    "31": "flat-coated_retriever",
    "32": "golden_retriever",
    "33": "Labrador_retriever",
    "34": "Chesapeake_Bay_retriever",
    "35": "Irish_setter",
    "36": "Gordon_setter",
    "37": "Brittany_spaniel",
    "38": "Welsh_springer_spaniel",
    "39": "cocker_spaniel",
    "40": "Sussex_spaniel",
    "41": "Irish_water_spaniel",
    "42": "briard",
    "43": "kelpie",
    "44": "Shetland_sheepdog",
    "45": "collie",
    "46": "Rottweiler",
    "47": "Doberman",
    "48": "boxer",
    "49": "Tibetan_mastiff",
    "50": "malamute",
    "51": "Siberian_husky",
    "52": "pug",
    "53": "Leonberg",
    "54": "Newfoundland",
    "55": "Great_Pyrenees",
    "56": "Samoyed",
    "57": "Pomeranian",
    "58": "chow",
    "59": "standard_poodle",
    "60": "dingo",
}
